<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Paramètres d'affichage</title>
<link rel="stylesheet" type="text/css" href="./colors/color1/view.css" media="all">
<script type="text/javascript" src="js/view.js"></script>
<script type="text/javascript" src="js/calendar.js"></script>
</head>
<body id="main_body" >
	
	<img id="top" src="images/top.png" alt="">
	<div id="form_container">
	
		<h1><a>Paramètres d'affichage</a></h1>
		<form id="form_1079780" class="appnitro"  method="post" action="/formbuilder/view.php">
					<div class="form_description">
			<h2>Paramètres d'affichage</h2>
			<p>Informations pour la gestion et affichage du slide</p>
		</div>						
			<ul >
			
					<li id="li_2" >
		<label class="description" for="element_2">Durée d'affichage </label>
		<span>
			<input id="element_2_1" name="element_2_1" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_2_1">Temporaire</label>
<input id="element_2_2" name="element_2_2" class="element checkbox" type="checkbox" value="1" />
<label class="choice" for="element_2_2">Permanent</label>

		</span> 
		</li>		<li id="li_1" >
		<label class="description" for="element_1">Descriptif pour la gestion (optionnel) </label>
		<div>
			<textarea id="element_1" name="element_1" class="element textarea small"></textarea> 
		</div><p class="guidelines" id="guide_1"><small>Information pour la partie de gestion des slides</small></p> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="1079780" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="images/bottom.png" alt="">
	</body>
</html>
